version: "3.9"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
    volumes:
      - dbData:/var/lib/mysql
